/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package cuccovillo.alessio.pdfsplitmerge.gui;

import cuccovillo.alessio.pdfsplitmerge.i18n.I18NLoader;

/**
 *
 * @author Alessio.Cuccovillo
 */
public class About extends javax.swing.JDialog {

    /**
     * Creates new form About
     * @param parent
     * @param modal
     */
    public About(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        slideUpDownText1 = new cuccovillo.alessio.pdfsplitmerge.gui.component.SlideUpDownText();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(I18NLoader.getString("about.title")); // NOI18N

        btnClose.setText(I18NLoader.getString("about.btnClose.text")); // NOI18N
        jPanel1.add(btnClose);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        slideUpDownText1.setBackground(new java.awt.Color(0, 0, 0));
        slideUpDownText1.setForeground(new java.awt.Color(0, 204, 0));
        slideUpDownText1.setSpeed(500);
        slideUpDownText1.setStarted(true);
        slideUpDownText1.setText("Ciao,\ncome stai?\n\nIo bene e tu?\n\n\tBene grazie!");

        javax.swing.GroupLayout slideUpDownText1Layout = new javax.swing.GroupLayout(slideUpDownText1);
        slideUpDownText1.setLayout(slideUpDownText1Layout);
        slideUpDownText1Layout.setHorizontalGroup(
            slideUpDownText1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );
        slideUpDownText1Layout.setVerticalGroup(
            slideUpDownText1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 263, Short.MAX_VALUE)
        );

        getContentPane().add(slideUpDownText1, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 622, 344);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private cuccovillo.alessio.pdfsplitmerge.gui.component.SlideUpDownText slideUpDownText1;
    // End of variables declaration//GEN-END:variables
}
